# -*- coding: utf-8 -*-
"""GS I.A 1 semestre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEqMbsFvCvMmbe8lHiOx4Mih8t9KHQOB

Ollama
"""

# 1. Instalar o zstd primeiro
!apt-get update && apt-get install -y zstd

# 2. Rodar a instalação do Ollama
!curl -fsSL https://ollama.com/install.sh | sh

# Instala o núcleo do LangChain e as integrações necessárias
!pip install langchain langchain-community langchain-ollama
!ollama pull nomic-embed-text
!pip install -q langchain-text-splitters

from langchain_ollama import OllamaEmbeddings
from langchain_community.vectorstores import InMemoryVectorStore
from langchain_community.embeddings import OllamaEmbeddings

# Isso cria a ponte entre seu código e o servidor Ollama rodando localmente
embeddings = OllamaEmbeddings(
    model="nomic-embed-text",
    base_url="http://localhost:11434"
)

!pip install -q pypdf

import subprocess, time, os
from langchain_core.vectorstores import InMemoryVectorStore
!ollama pull nomic-embed-text
subprocess.Popen(["ollama", "serve"])
time.sleep(3)

!ollama pull llama3.2:1b

!pip install ollama -q

import ollama

# Inicia o servidor Ollama em segundo plano e direciona a saída para não poluir o log
process = subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# IMPORTANTE: Dê um tempo para o servidor carregar totalmente na memória
time.sleep(10)
print("Servidor Ollama iniciado!")

"""**Chat GPT**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --quiet --upgrade langchain-text-splitters langchain-community langgraph langchain-openai langchain-core pypdf unstructured

import openai
from openai import OpenAI
from google.colab import userdata

# configurando chatgpt
import getpass
import os
from google.colab import userdata
from langchain.chat_models import init_chat_model
from langchain_core.vectorstores import InMemoryVectorStore

os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
llm = init_chat_model("gpt-4o-mini", model_provider="openai")

#selecionando o embedding
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-ada-002")

"""**Usado Para ambos Modelos**"""

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# 1. Carregar o arquivo (ex: 'Manual de instrução.pdf')
# Se for .txt, use TextLoader('Manual de instrução.txt')
loader = PyPDFLoader("Manual de instrução.pdf")
documento = loader.load()

# 2. Configurar o divisor de texto
# Como o manual possui tabelas, um chunk_size de 500 a 1000 costuma preservar bem o contexto
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

# 3. Gerar os chunks
docs = splitter.split_documents(documento)

print(f"Total de chunks criados: {len(docs)}")

from langchain_core.vectorstores import InMemoryVectorStore

# Cria o store em memória e adiciona os documentos (o store já gera os embeddings automaticamente)
vector_store = InMemoryVectorStore(embeddings)
vector_store.add_documents(docs)



"""**Agentes de I.A**"""

# uso simples
client = OpenAI(api_key=userdata.get('OPENAI_API_KEY'))

response = client.responses.create(
    model="gpt-4o-mini",
    input="o que é a vida?",
    temperature=2,
    max_output_tokens=500,

)

print(response.output_text)

def agentPegarDadosAleatorios():
  resposta = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
    {
    "role": "system",
    "content": f'''Você é um sistema de controle de missão espacial. Voce deve gerar dados falsos como: Temperatura (em °C), Bateria (em %), Comunicação (em %)
    Oxigênio (em %), Estabilidade (em %).
    O output deve ser apenas o a classifição e o resultado. Por exemplo
    Temperatura: 25°C
    Bateria: 10%
    Devemos ter apenas um resultado por topico. Devemos ter um valor para temperatura, outro para bateria etc
    '''
    },
    {
    "role": "user",
    "content": "Mostre os resultados gerados aleatoriamente"
    },
    {
    "role":"assistant",
    "content": '''Temperatura : 25°C
      Bateria : 10%
      Comunicação: 90%
      Oxigênio: 75%
      Estabilidade: 80%''',
    },
     {
    "role": "user",
    "content": "Mostre os resultados gerados aleatoriamente"
    }
    ]
  )

  print("Ola, os dados aleatorios foram gerado e esta pronto para uso!")
  print(resposta.choices[0].message.content)
  return resposta.choices[0].message.content

agentPegarDadosAleatorios()

def agentPesquisaSemantica(dados,manualContent):
  resposta = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
    {
    "role": "system",
    "content": f'''Você é um sistema de controle de missão espacial. O usuario ira enviar os dados e o manual para vc consultar e gerar as classificacoes para cada topico (Temperatura, Bateria, etc)
    Por exemplo. Caso a temperatura seja 32, a classificacao deve ser "Atençao". Caso a comunicação seja 75%, a classificação deve ser "Normal". APENAS GERE A CLASSIFICAÇÂO. Nao coloque pontuação
    '''
    },
    {
    "role": "user",
    "content": '''
    Temperatura: **25°C**
    Bateria: 10%
    Comunicação: 90%
    Oxigênio: 75%
    Estabilidade: 80%"'''
    },{
    "role": "assistant",
    "content": '''
    Temperatura: NORMAL
    Bateria: CRÍTICO
    Comunicação: NORMAL
    Oxigênio: CRÍTICO
    Estabilidade: NORMAL"'''
    },
    {
    "role": "user",
    "content": f"Dados:{dados} Manual:{manualContent}. Se houver isso no texto, remova: Pontuação total, Classificação do ciclo"
    }
    ]
  )

  print("Após minha pesquisa cautelosa, aqui estão os dados gerados:")
  print()
  print(resposta.choices[0].message.content)
  return resposta.choices[0].message.content

def agentPontuadorRisco(dados,manualContent):
  resposta = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
    {
    "role": "system",
    "content": f'''Você é um sistema de controle de missão espacial.  O usuario ira enviar os dados e o manual para vc consultar e  gerar as a quantidade de pontos total para cada topico (Temperatura, Bateria, etc)
    Por exemplo. Caso a classificação da temperatura seja NORMAL, devemos ter 0 pontos. Caso a classificação da comunicação seja Critico, devemos ter 2 pontos.
    O output deve vc mostrar cada classificação e o ponto de cada uma. Vc deve criar um "Total Pontos" e mostrar a soma de todos os pontos
    '''
    },
    {
    "role": "user",
    "content": '''
    Manutenção: Normal
    Oxigênio: Atenção
    Temperatura: Normal
    Bateria: Atenção
    Comunicação: Normal
    Estabilidade: Atenção'''
    },{
    "role": "assistant",
    "content": '''
    Manutenção: 0 pontos
    Oxigênio: 1 ponto
    Temperatura: 0 pontos
    Bateria: 1 ponto
    Comunicação: 0 pontos
    Estabilidade: 1 ponto

    Pontuação Total = 3 pontos
    '''},
    {
    "role": "user",
    "content": f"Dados:{dados} Manual:{manualContent}"
    }

    ]
  )

  print("Minha responsabilidade é saber quantos pontos temos para saber como a missão está, aqui estão os dados gerados com os pontos de cada classificação:")
  print()
  print(resposta.choices[0].message.content)
  return resposta.choices[0].message.content

def agentTotalClassificação(dados,manualContent):
  resposta = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
    {
    "role": "system",
    "content": f'''Você é um sistema de controle de missão espacial. Você possui os dados {dados} e precisa atraves do {manualContent} verificar o status da missão
    Para fazer isso, você deve usar o total de pontos. O resultado deve ser o status da missão.

    '''
    },
    {
    "role": "user",
    "content": "Mostre os resultados gerados. Quero apenas o status da missao"
    }
    ]
  )

  print("Após minha pesquisa cautelosa, aqui estão os dados gerados:")
  print()
  print(resposta.choices[0].message.content)
  return resposta.choices[0].message.content

"""**Código principal**"""

print("Olá, seja bem vindo á nosso sistema inteligente. Iremos executar agora a analise completa do sistema")
print()
dadosAleatorios = agentPegarDadosAleatorios()

dadosAleatorios = '''Temperatura: 40°C
Bateria: 10%
Comunicação: 15%
Oxigênio: 12%
Estabilidade: 10% '''

# Vamos fazer uma pesquisa semantica para fazer a metodologia RAG. assim, podemos passar para nosso proximo agente
results = vector_store.similarity_search(dadosAleatorios, k=5)
bancoVetorialContent = ""
for res in results:
    bancoVetorialContent += res.page_content

print(bancoVetorialContent)

pesquisaSemantica = agentPesquisaSemantica(dadosAleatorios,bancoVetorialContent)

pontosRiscos = agentPontuadorRisco(pesquisaSemantica,bancoVetorialContent)

classificacaoFinal = agentTotalClassificação(pontosRiscos,bancoVetorialContent)

print()

print("Fim da classificação")